name: brew_flutter
description: A Flutter frontend for homebrew

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.19.1 <3.0.0"
  flutter: "3.7.1"

dependencies:
  cupertino_icons: ^1.0.4
  dartx: ^1.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  fpdart: ^0.4.0
  freezed_annotation: ^2.0.3
  hooks_riverpod: ^2.1.3
  linkable: ^3.0.1
  macos_ui: ^1.4.1
  rxdart: ^0.27.3
  timeago: ^3.2.2
  url_launcher: ^6.1.2

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  very_good_analysis: ^3.0.0

flutter:
  fonts:
    - family: SourceCodePro
      fonts:
        - asset: fonts/SourceCodePro-Regular.ttf
