name: brew_flutter
description: A Flutter frontend for homebrew

publish_to: "none"

version: 0.1.0+2

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: "3.19.5"

dependencies:
  cupertino_icons: ^1.0.8
  dartx: ^1.2.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.5.1
  linkable: ^3.0.2
  macos_ui: ^2.0.5
  rxdart: ^0.27.7
  timeago: ^3.6.1
  url_launcher: ^6.2.6

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  very_good_analysis: ^5.1.0

flutter:
  fonts:
    - family: SourceCodePro
      fonts:
        - asset: fonts/SourceCodePro-Regular.ttf
